apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: sparkleboss/resultserver
        name: resultserver
        ports:
          - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_admin_password
        envFrom:
          - configMapRef:
              name: server-config
        resources: {}
